//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabotaDlyaTrpo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Romb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Romb()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id_Romb { get; set; }
        public Nullable<double> Storona { get; set; }
        public Nullable<double> Ugol { get; set; }
        public Nullable<double> Diagonal1 { get; set; }
        public Nullable<double> Digannal2 { get; set; }
        public double Ploschad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
    }
}
