//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabotaDlyaTrpo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_romb
    {
        public int Nomer_romba { get; set; }
        public int Id_User { get; set; }
    
        public virtual Romb Romb { get; set; }
    }
}
