//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RabotaDlyaTrpo
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZavpisvZhurnale
    {
        public int Id_Zapisi { get; set; }
        public int Id_User { get; set; }
        public System.DateTime Data { get; set; }
        public int Id_Deistviya { get; set; }
        public string Nazvanie_deistviya { get; set; }
        public string Login_user { get; set; }
    
        public virtual Spravochnik Spravochnik { get; set; }
        public virtual User User { get; set; }
    }
}
